### ISSUE TITLE
The trailer uses commercial music, leaving the video vulnerable to take-down notices

### ISSUE THREAD

**Issue by computamike** [JonnyBurger/remotion-trailer#3]
Rather than using a commercial song - like Voices In my Head by Skinny Days & CLMD, the trailer should use some other form of data.

If the label became aware that this track was being used - then (depending on the popularity of the video) they _may_ want to pull the video, or grab monetization.  I'm not a lawyer - but some free and open source music would avoid this scenario.

Label in question seems to be "The Selective Label" - a division of Sony Music Entertainment Norway.

Of course it might be that the developer has all of the appropriate licences - in which case please close this issue.

# Counter Arguments

- **I'm only using 10 seconds - surely they'll be cool about that?**
_I believe that any use of copyrighted matterial would be in violation_
- **But as I'm only using 10 secods they won't know right?**
_It's probably correct that contentid won't flag a small section - but when videos become more popular then may become aware of this issue._
- **So they take down my video - big deal.**
_Well - it could be a big deal.  Copyright strikes on Youtube could allow them (or the claiming companies) to close your channel down.  Hopefully your channel will start to fill with tutorials and value-add training matterial for remotion - and it would be a shame to lose that content._
- **It's too hard to change the audio track now**
_I believe that all you would need to do would be to remix the audio track with difference music at the end.  Free and Open Source music can be sourced from the internet.  I think it is even possible to replace an audio track using Youtube's own video tools_

[Creative Commons](https://creativecommons.org/about/program-areas/arts-culture/arts-culture-resources/legalmusicforvideos/) has a collection of sources that can be used.

**Comment by JonnyBurger** [comment]
This is a very good point!
I will change the music soon. The question is, what song to use? Someone with a suggestion? Can also consider spending a little on a music platform like Audiojungle.

**Comment by JonnyBurger** [comment]
I removed it for now! Thanks for the suggestion!
