### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by computamike** [JonnyBurger/remotion-trailer#6]
I was wondering if there might be scope to create a GitHub Action, that can be used to build your remotion video?  This would make video production more like a CI/CD Process.

Years ago I did something similar using KdenLive and Jenkins - the result was this video here : 

[![Alt text](https://img.youtube.com/vi/cul1CAh_Pio/0.jpg)](https://www.youtube.com/watch?v=cul1CAh_Pio)

It might even automatically upload the generated video file to your YouTube channel, while also making the video file available for download.

**Comment by JonnyBurger** [comment]
Very nice idea! Consider it done! 😁 🥳

https://github.com/JonnyBurger/remotion-trailer/actions/runs/586704100
